import { Knex } from 'knex';
import { ETableNames } from '../ETableNames';

export const seed = async(knex: Knex)  => {
    const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number}]>('* as count');
    if(!Number.isInteger(count) || Number(count) > 0 ) return;

    const cidadesToInsert = cidades.map(nomeDaCidade => ({nome: nomeDaCidade}));
    await knex(ETableNames.cidade).insert(cidadesToInsert);
};

const cidades = [
    'São Paulo',
    'Guarulhos',
    'Campinas',
    'São Bernardo do Campo',
    'São José dos Campos',
    'Santo André',
    'Ribeirão Preto',
    'Osasco',
    'Sorocaba',
    'Mauá',
    'Santos',
    'Diadema',
    'Jundiaí',
    'Piracicaba',
    'Carapicuíba',
    'Bauru',
    'Itaquaquecetuba',
    'São Vicente',
    'Franca',
    'Suzano',
    'Taboão da Serra',
    'Barueri',
    'Taubaté',
    'São Caetano do Sul',
    'Embu das Artes',
    'Jacareí',
    'Limeira',
    'Hortolândia',
    'São José do Rio Preto',
    'Mogi das Cruzes',
    'Americana',
    'Araraquara',
    'Itapevi',
    'Indaiatuba',
    'Cotia',
    'Pirassununga',
    'Rio Claro',
    'Marília',
    'Itu',
    'Itapetininga',
    'Araçatuba',
    'Pindamonhangaba',
    'Botucatu',
    'Sumaré',
    'Suzano',
    'Mogi Guaçu',
    'Cubatão',
    'Valinhos',
    'Ribeirão Pires',
    'Ourinhos',
    'Bragança Paulista',
    'Atibaia',
    'Poá',
    'Sertãozinho',
    'Santa Bárbara d\'Oeste',
    'Francisco Morato',
    'Itatiba',
    'Catanduva',
    'Ilhabela',
    'Registro',
    'Jaú',
    'Votuporanga',
    'Lorena',
    'Araras',
    'Itanhaém',
    'São Carlos',
    'Ferraz de Vasconcelos',
    'Avaré',
    'Matão',
    'Salto',
    'Itapeva',
    'Assis',
    'Ituverava',
    'Lins',
    'Caieiras',
    'Itapira',
    'Assis',
    'Leme',
    'Votorantim',
    'Sertãozinho',
    'Tatuí',
    'Várzea Paulista',
    'Biritiba-Mirim',
    'Caçapava',
    'Mairinque',
    'Valparaíso',
    'Cajamar',
    'Piedade',
    'Santa Fé do Sul',
    'Jales',
    'Mococa',
    'Tupã',
    'São Sebastião',
    'Adamantina',
    'Santa Cruz do Rio Pardo',
    'Barretos',
    'São João da Boa Vista',
    'Bariri',
    'Ibitinga',
    'Penápolis',
    'Guararema',
    'Dracena',
    'Pereira Barreto',
    'Lençóis Paulista',
    'São Roque',
    'Marília',
    'Paraguaçu Paulista',
    'Tietê',
    'Capivari',
    'Taquaritinga',
    'Vargem Grande Paulista',
    'Itupeva',
    'São Manuel',
    'Salto de Pirapora',
    'Espírito Santo do Pinhal',
    'Igarapava',
    'Tambaú',
    'Nova Odessa',
    'São Joaquim da Barra',
    'Cruzeiro',
    'São Pedro',
    'Iperó',
    'Pederneiras',
    'Cerquilho',
    'Conchal',
    'Iracemápolis',
    'Eldorado',
    'Monte Aprazível',
    'Lucélia',
    'Andradina',
    'Presidente Prudente',
    'Rancharia',
    'Tupi Paulista',
    'Santana de Parnaíba',
    'Ibiúna',
    'Cabreúva',
    'Itararé',
    'Itapevi',
    'São Lourenço da Serra',
    'Juquitiba',
    'Embu-Guaçu',
    'São Miguel Arcanjo',
    'Sarapuí',
    'Guarujá',
    'Bertioga',
    'São Vicente',
    'Cubatão',
    'Praia Grande',
    'São Sebastião',
    'Caraguatatuba',
    'Ubatuba',
    'Ilhabela',
    'São José dos Campos',
    'Jacareí',
    'Caçapava',
    'Taubaté',
    'Tremembé',
    'Pindamonhangaba',
    'Guaratinguetá',
    'Cruzeiro',
    'Lorena',
    'Potim',
    'Roseira',
    'Cunha',
    'Aparecida',
    'Canas',
    'Bananal',
    'São Bento do Sapucaí',
    'Campos do Jordão',
    'Monteiro Lobato',
    'Santo Antônio do Pinhal',
    'Redenção da Serra',
    'Natividade da Serra',
    'São Luiz do Paraitinga',
    'Ubatuba',
    'Caraguatatuba',
    'Ilhabela',
];